services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: dev
        UID: 1000
        GID: 1000
    working_dir: /app
    volumes:
      - .:/app:cached
    env_file:
      - .env_dev
    stdin_open: true
    tty: true
    init: true
    command: sleep infinity
