# name: CI

# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository (with submodules)
#         uses: actions/checkout@v4
#         with:
#           submodules: recursive
#           fetch-depth: 0

#       - name: Show directory tree
#         run: |
#           ls -la
#           ls -la external || true
